require: rubocop-rspec

AllCops:
  Exclude:
    - bin/bundle

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: true
  Max: 20

RSpec/MultipleExpectations:
  Enabled: true
  Max: 5

RSpec/ExampleLength:
  Max: 25

RSpec/MessageSpies:
  Enabled: false